# Generated by Django 2.2.4 on 2019-11-01 15:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import mdeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='news',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style', models.CharField(choices=[('科技', 'tech'), ('时政', 'political'), ('经济', 'ecomony'), ('军事', 'military')], max_length=6)),
                ('news_title', models.CharField(max_length=200)),
                ('date', models.DateTimeField(auto_now=True)),
                ('text', mdeditor.fields.MDTextField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='writer',
            fields=[
                ('writer_name', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='name')),
                ('password', models.CharField(max_length=20)),
                ('is_active', models.IntegerField(choices=[(0, 'false'), (1, 'true')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_path', models.FileField(upload_to='video/', verbose_name='视频')),
                ('name', models.CharField(default=django.utils.timezone.now, max_length=50)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.news')),
            ],
        ),
        migrations.AddField(
            model_name='news',
            name='writer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.writer'),
        ),
        migrations.CreateModel(
            name='img',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=50)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.news')),
            ],
        ),
    ]
