# Generated by Django 2.2.4 on 2019-11-01 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_path',
            field=models.FileField(upload_to='static/video/', verbose_name='视频'),
        ),
    ]
