# Generated by Django 2.2.4 on 2019-11-20 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20191109_1003'),
    ]

    operations = [
      
      
    ]
